name: DEPLOY - PROD
on:
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID_PROD}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY_PROD}}
  TF_VAR_environment: PROD
  TF_VAR_boilerplate_laravel_10_serverless_app_key: ${{secrets.BOILERPLATE_LARAVEL_APP_KEY_PROD}}
  TF_VAR_boilerplate_laravel_10_serverless_jwt_secret: ${{secrets.BOILERPLATE_LARAVEL_JWT_SECRET_PROD}}
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.2.0"
      - name: Init
        run: terraform init
      - name: Validate
        run: terraform validate
      - name: Select or Create Workspace
        run: |
          terraform workspace list | grep -q "prod"
          if [ $? -ne 0 ]; then
            terraform workspace new prod
          else
            terraform workspace select prod
          fi
      - name: Plan
        run: terraform plan -out plan.out
      - name: Apply
        run: terraform apply plan.out
