name: DESTROY
on:
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID_DEV}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY_DEV}}
  TF_VAR_environment: DEV
  TF_VAR_boilerplate_laravel_10_serverless_app_key: ${{secrets.BOILERPLATE_LARAVEL_APP_KEY_DEV}}
  TF_VAR_boilerplate_laravel_10_serverless_jwt_secret: ${{secrets.BOILERPLATE_LARAVEL_JWT_SECRET_DEV}}
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.2.0"
      - name: Init
        run: terraform init
      - name: Validate
        run: terraform validate
      - name: Select workspace
        run: terraform workspace select dev
      - name: Destroy
        run: terraform destroy -auto-approve
